### PR TITLE
Shobu95 Profile Card Added + fixed some alignment and overflow issues

### PR DESCRIPTION
**Pull request by Shobu95**
Hello, i have pushed the following changes and updates to your repository, following the rules as mentioned in your CONTRIBUTORS.md file.

1- Added my developer profile in the Members list.
2- Faced an overflow issue at the bottom of the welcome screen, fixed that. (I have a 5 inch screen phone)
3- Fixed the alignment of the content inside the list tiles of the Contributor's list shown in DeveloperScreen.
4- Faced and overflow issue at the bottom of the member-info screen, fixed it using ScrollView.

### CODE REVIEW

**Comment by sarveshsrv** [comment]
Looks good but what changes you have made in the Gradle? That was not supposed to be changed, plz look into it @Shobu95

**Comment by Shobu95** [comment]
> Looks good but what changes you have made in the Gradle? That was not supposed to be changed, plz look into it @Shobu95

Those changes were made by the framework while building the app. I didn't do them explicitly. Should i revert them?

**Comment by sarveshsrv** [comment]
Have you made these changes on Mac or Windows @Shobu95 ? Anyways I'll look into it.

**Comment by Shobu95** [comment]
Ubuntu 20.04.1 LTS, sir.

**Pull request merged**
